import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Cpu, Gauge, MapPin, Plus, X } from 'lucide-react'
import { api, ApiError } from '../lib/api'
import { deriveMachineStatus } from '../lib/monitoring'
import MachineIllustration from '../components/monitoring/MachineIllustration'
import { SearchBox, State, Surface } from './OperationsPage'

const STATUS = { healthy: ['Saudável', '#10b981'], watch: ['Atenção', '#f59e0b'], critical: ['Crítico', '#dc2626'], unknown: ['Sem dados', '#64748b'] }

export default function EquipmentPage() {
  const [rows, setRows] = useState([]); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const [creating, setCreating] = useState(false)
  const load = () => api.listAllMachines().then((data) => setRows(Array.isArray(data) ? data : data?.items ?? [])).catch((err) => setError(err instanceof ApiError ? err.message : 'Não foi possível carregar os equipamentos.')).finally(() => setLoading(false))
  useEffect(() => { load() }, []) // eslint-disable-line react-hooks/exhaustive-deps
  const visible = useMemo(() => { const q = query.toLowerCase(); return rows.filter((row) => !q || [row.name, row.tag, row.location, row.monitoringName].some((v) => String(v ?? '').toLowerCase().includes(q))) }, [rows, query])
  const actions = <button onClick={() => setCreating(true)} className="flex items-center gap-1.5 px-3.5 py-2 rounded-lg text-xs font-semibold text-white" style={{ background: '#059669' }}><Plus size={12} />Novo equipamento</button>
  return <Surface title="Equipamentos" subtitle="Ativos industriais independentes, associáveis a processos e monitoramentos." icon={Cpu} actions={actions}>
    {creating && <CreateEquipmentModal onClose={() => setCreating(false)} onCreate={async (data) => { await api.createEquipment(data); setCreating(false); load() }} />}
    <SearchBox value={query} onChange={setQuery} placeholder="Buscar equipamento, TAG ou localização…" />
    {loading ? <State>Carregando…</State> : error ? <State error>{error}</State> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{visible.map((machine) => { const status = deriveMachineStatus(machine); const meta = STATUS[status] ?? STATUS.unknown; return <Link key={machine.id} to={`/equipment/${machine.id}`} className="rounded-xl border border-border overflow-hidden no-underline" style={{ background: '#111520' }}><div className="relative h-32" style={{ background: '#080c14' }}><MachineIllustration kind={machine.kind} /><span className="absolute top-2 right-2 text-[10px] px-2 py-0.5 rounded-full" style={{ color: meta[1], background: `${meta[1]}22` }}>{meta[0]}</span></div><div className="p-3"><p className="text-xs font-semibold text-foreground truncate">{machine.name}</p><div className="flex gap-3 mt-1 text-[10px] text-muted-foreground"><span><Gauge size={10} className="inline mr-1" />{machine.parameters?.length ?? machine.parameterCount ?? 0}</span>{machine.location && <span className="truncate"><MapPin size={10} className="inline mr-1" />{machine.location}</span>}</div>{machine.monitoringName && <p className="text-[10px] text-emerald-400 mt-2 truncate">{machine.monitoringName}</p>}</div></Link> })}{!visible.length && <State>Nenhum equipamento encontrado.</State>}</div>}
  </Surface>
}

function CreateEquipmentModal({ onClose, onCreate }) {
  const [values, setValues] = useState({ name: '', kind: 'generico', tag: '', location: '', manufacturer: '', model: '' }); const [busy, setBusy] = useState(false)
  const field = (key, placeholder) => <input value={values[key]} onChange={(event) => setValues((current) => ({ ...current, [key]: event.target.value }))} placeholder={placeholder} className="px-3 py-2 rounded-lg border border-border text-xs text-foreground" style={{ background: '#0d1017' }} />
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ background: 'rgba(3,6,12,.78)' }}><form onSubmit={async (event) => { event.preventDefault(); if (!values.name.trim()) return; setBusy(true); try { await onCreate(values) } finally { setBusy(false) } }} className="w-full rounded-xl border border-border" style={{ maxWidth: 480, background: '#111520' }}><div className="flex justify-between px-4 py-3 border-b border-border"><div><h2 className="text-sm font-semibold text-foreground">Cadastrar equipamento</h2><p className="text-[11px] text-muted-foreground mt-1">Crie o ativo antes de associá-lo a processos ou monitoramentos.</p></div><button type="button" onClick={onClose}><X size={13} /></button></div><div className="grid gap-3 p-4 sm:grid-cols-2"><label className="flex flex-col gap-1 text-[10px] text-muted-foreground sm:col-span-2">Nome *{field('name', 'Ex.: Torno CNC Prod1')}</label><label className="flex flex-col gap-1 text-[10px] text-muted-foreground">Tipo<select value={values.kind} onChange={(event) => setValues((current) => ({ ...current, kind: event.target.value }))} className="px-3 py-2 rounded-lg border border-border text-xs text-foreground" style={{ background: '#0d1017' }}><option value="torno">Torno CNC</option><option value="fresadora">Fresadora</option><option value="compressor">Compressor</option><option value="esteira">Esteira</option><option value="generico">Genérico</option></select></label><label className="flex flex-col gap-1 text-[10px] text-muted-foreground">TAG{field('tag', 'Ex.: TRN-01')}</label><label className="flex flex-col gap-1 text-[10px] text-muted-foreground">Fabricante{field('manufacturer', 'Ex.: Romi')}</label><label className="flex flex-col gap-1 text-[10px] text-muted-foreground">Modelo{field('model', 'Ex.: GL 240')}</label><label className="flex flex-col gap-1 text-[10px] text-muted-foreground sm:col-span-2">Localização{field('location', 'Ex.: Célula 01')}</label></div><div className="flex justify-end gap-2 px-4 py-3 border-t border-border"><button type="button" onClick={onClose} className="px-3 py-2 text-xs text-muted-foreground">Cancelar</button><button disabled={busy || !values.name.trim()} className="px-3 py-2 rounded-lg text-xs font-semibold text-white disabled:opacity-50" style={{ background: '#059669' }}>{busy ? 'Cadastrando…' : 'Cadastrar'}</button></div></form></div>
}
